### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by kalmou** [derickongeri/shoreline_extractor#15]
To install plugins CoGEOS

**Comment by Kevin-Kiprotich** [comment]
Kindly share an image of the error that you get when installing

**Comment by kalmou** [comment]
J'ai eu solution par rapport au problème que j'avais.

**Comment by kalmou** [comment]
C'est le résultat que j'ai obtenu.

**Comment by kalmou** [comment]
![IMG-20240212-WA0015](https://github.com/derickongeri/shoreline_extractor/assets/123183729/abb54011-2e21-4883-8174-cdb35f963409)
Le résultat

**Comment by Kevin-Kiprotich** [comment]
This is good.
